export default {
    SPLASH_SCREEN: 'splashScreen',
    ONBOARDING_SCREENS:'OnboardingScreen',
    LOGIN:'Login',
    SIGN_UP:'signUp',
    FORGET_PASSWORD: 'forgetPassword',
    SETTING_SCREENS_STACK: 'settingScreenStack',
    HOME_STACK: 'homeStack',
    PROFILE: 'profile',
    HOME_SCREEN:'homeScreen',
    SEARCH_SCREEN: 'searchScreen',
    SEARCH_STACK: 'searchStack',
    MAIN_BOTTOM_TAB_STACK:'mainBottomTabStack',
    HOME_DRAWER:'homeDrawer',
    SETTINGS_SCREEN: 'settingScreen',
    YOUR_LIBRARY_SCREEN: 'yourLibrary',
    YOUR_LIBRARY_STACK: 'yourLibraryStack',
    PREMIUM_SCREEN:'premiumScreen',
    PREMIUM_STACK: 'premiumStack'
}